import { useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { PopulatedPost } from "../../types/posts";

export default function PostView() {
  const router = useRouter();
  const [post, setPost] = useState<PopulatedPost>();
  const { id } = router.query;
  useEffect(() => {
    console.log(id);
    fetchPost();
  }, []);
  const fetchPost = async () => {
    const post = await fetch(`/api/posts/findone`, {
      method: "POST",
      body: JSON.stringify({ id }),
    });
    const parsed = await post.json();
    setPost(parsed);
  };
  const { data: session } = useSession();
  return (
    <>
      <Head>
        <title>{post?.title || "Post Details"}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Write posts, let others read" />
        <meta
          name="robots"
          content="nofollow, noindex, max-snippet:-1, max-video-preview:-1, max-image-preview:large"
        />

        <meta property="og:locale" content="en_US" />
        <meta property="og:type" content="website" />
        <meta property="og:title" content="Qwestive: We read your thoughts" />
        <meta
          property="og:description"
          content="Come and read, come and write"
        />
        <meta property="og:url" content="https://www.qwestive.io/" />
        <meta property="og:site_name" content="qwestive" />
        <meta
          property="og:image"
          content="https://www.qwestive.io/illustration.svg"
        />
        <meta property="og:image:width" content="1200" />
        <meta property="og:image:height" content="630" />
        <meta property="og:image:alt" content="Qwestive" />
        <meta property="og:image:type" content="image/svg" />

        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content={post?.title || "Post Details"} />
        <meta
          name="twitter:description"
          content={post?.title || "Post Details"}
        />
        <meta property="twitter:card" content="summary_large_image" />
        <meta
          property="twitter:image"
          content="https://qwestive.io/illustration.svg"
        />
        <meta
          property="twitter:image:alt"
          content={post?.title || "Post Details"}
        />
      </Head>
      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4 md:w-2/3 gap-2">
        <h1 className="text-3xl md:text-[3rem] leading-normal font-extrabold text-gray-700">
          {post?.title}
        </h1>
        <img src={post?.image || "/loading.svg"}></img>
        <p>{post?.content}</p>
        <h3 className="text-2xl md:text-[2rem] leading-normal font-extrabold text-gray-700">
          By: {post?.author?.name}
        </h3>
        {session && session.user?.id === post?.author.id && (
          <button
            onClick={() => router.push(`/modify/${post?.id}`)}
            className="bg-violet-500 hover:bg-violet-700 text-white font-bold py-2 px-4 rounded"
          >
            Edit
          </button>
        )}
        <button
          onClick={() => router.push("/")}
          className="bg-gray-200 hover:bg-gray-400 font-bold py-2 px-4 rounded text-black"
        >
          Go to posts
        </button>
      </main>
    </>
  );
}
